id = "neovim-minimal"
name = "Neovim Minimal"
version = "0.1.0"
schema_version = 2
authors = ["Maroisa"]
description = "Zed neovim minimal, modified from Kim Nørgaard's"
repository = "https://github.com/maroisa/zed-neovim-minimal"
